### ISSUE TITLE
Tetris pieces don't display while falling

### ISSUE THREAD

**Issue by qpwo** [NivenT/RGB#1]
I downloaded and ran [tetris](http://www.emuparadise.me/Nintendo_Game_Boy_ROMs/Tetris_%28World%29/69822) and when I got to main gameplay, the pieces weren't displayed until they landed. I guess this falls under the known issue of sprite displaying. Thought it might be helpful to have a specific known example.

![tetris](https://cloud.githubusercontent.com/assets/10591373/18474629/f66f4d46-7990-11e6-87d1-f5ff23657bb4.png)

**Comment by NivenT** [comment]
This was actually an unknown issue. The problem was that sprites are always supposed to be displayed over the background if it has color 0, but I had accidentally gotten rid of the check for that in a previous commit so the background was given priority. It should work fine now.
