### ISSUE TITLE
Dr. Mario freezes after pressing enter on the title screen

### ISSUE THREAD

**Issue by mattbruv** [NivenT/RGB#2]
I'm working on my own emulator, and I remember seeing this issue in your README while I was looking at rust GB emus. I have just gotten to the point where I am trying to get Dr. Mario running, and it froze before starting a game too. Check out [this post](https://www.reddit.com/r/EmuDev/comments/4w6479/gb_dr_mario_level_generation_issues/d64j3nt/) about someone else who had the same problem.

I tried changing the STAT register to be set to mode 0 (HBlank) when the LCD is turned off, and Dr. Mario runs perfectly for me now. You may want to look into this, because I notice that you set the STAT register to mode 1 when the LCD is off, this may be where your problem lies.

**Comment by NivenT** [comment]
Wow, thanks. I changed it to set it 0, and it seems to be working now. I wonder why I had it set to 1 before...

**Comment by mattbruv** [comment]
No problem, glad I could help. I do know that there are so many different GB resources out there. A lot of them tend to be ambiguous, exclude small details or incorrectly document behavior. Even the official GB programming manual from Nintendo has a few errors in it. You may have easily read incorrect information. The good thing about these tiny bugs is that they are usually an easy fix when you do find the correct info.
